### ISSUE TITLE
Arcana RPG with Gendustry crashes my game

### ISSUE THREAD

**Issue by Jana08208** [quentin452/Arcana-RPG#17]
### Game log

https://pastebin.com/JXeXs2WN

### Description

Hi there! Firstly I wanna say that I am so happy someone took their time to continue development of this amazing mod. It had such potential when it first came, and now it has a chance to shine again. 

However, the mod seems to be incompatible with Gendustry. That was also a problem with the original upload of Arcana RPG. Is there a way to make them work together without crashing the game? Is there a way to fix this or am I out of luck?

Kind regards :)

**Comment by quentin452** [comment]
the bug is confirmed by me , so l'ill see if i can do something

**Comment by quentin452** [comment]
here is the devbuild that fix the issue https://mega.nz/file/r99WnCYS#UCcPldnQeRY7mmropntmp55cq-sdSO5pxvFvjG50tOE
