### ISSUE TITLE
Crashes when I take blade of paladin and right click

### ISSUE THREAD

**Issue by 167OSS** [quentin452/Arcana-RPG#30]
### Modpack

NO

### Game log

---- Minecraft Crash Report ----
// There are four lights!

Time: 24-1-19 上午9:58
Description: Ticking Particle

java.lang.NullPointerException: Ticking Particle
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:600)
	at net.minecraft.client.particle.EntityFireworkSparkFX.func_70071_h_(SourceFile:363)
	at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:77)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2055)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:600)
	at net.minecraft.client.particle.EntityFireworkSparkFX.func_70071_h_(SourceFile:363)
	at net.minecraft.client.particle.EffectRenderer.func_78868_a(EffectRenderer.java:77)

-- Particle being ticked --
Details:
	Particle: EntityFireworkSparkFX, Pos (75.27265644316513,84.10000000149012,416.05674714335385), RGBA (1.0,1.0,0.0,1.0), Age 29
	Particle Type: MISC_TEXTURE
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2055)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['yoruki_167'/268, l='MpServer', x=74.57, y=86.62, z=417.72]]
	Chunk stats: MultiplayerChunkCache: 560, 560
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (122,64,217), Chunk: (at 10,4,9 in 7,13; contains blocks 112,0,208 to 127,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3709 game time, 3709 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 128 total; [EntityVoidFiend['虚空领主小怪'/1284, l='MpServer', x=69.74, y=80.00, z=421.06], EntityVoidFiend['虚空领主小怪'/1285, l='MpServer', x=72.50, y=80.00, z=422.03], EntitySapientMiner['银色矿工'/269, l='MpServer', x=72.28, y=12.00, z=432.69], EntityCyclops['独眼巨人'/270, l='MpServer', x=78.00, y=25.00, z=427.97], EntitySpider['蜘蛛'/271, l='MpServer', x=69.34, y=25.00, z=433.63], EntityCreeper['爬行者'/272, l='MpServer', x=65.59, y=40.00, z=422.06], EntityCreeper['爬行者'/273, l='MpServer', x=74.50, y=45.00, z=418.50], EntityZombie['僵尸'/274, l='MpServer', x=74.66, y=45.00, z=419.38], EntityZombie['僵尸'/275, l='MpServer', x=67.34, y=45.00, z=420.34], EntityZombie['僵尸'/276, l='MpServer', x=70.34, y=45.00, z=421.34], EntityZombie['僵尸'/277, l='MpServer', x=69.16, y=40.00, z=414.78], EntityBat['蝙蝠'/278, l='MpServer', x=76.25, y=64.10, z=420.41], EntityVoidFiend['虚空领主小怪'/279, l='MpServer', x=65.72, y=80.00, z=421.88], EntityVoidFiend['虚空领主小怪'/280, l='MpServer', x=68.97, y=75.00, z=414.19], EntityClientPlayerMP['yoruki_167'/268, l='MpServer', x=74.57, y=86.62, z=417.72], EntitySapientMiner['银色矿工'/283, l='MpServer', x=75.72, y=12.00, z=438.31], EntitySapientMiner['银色矿工'/284, l='MpServer', x=76.41, y=12.00, z=439.22], EntityCyclops['独眼巨人'/286, l='MpServer', x=77.53, y=25.00, z=437.03], EntityCyclops['独眼巨人'/287, l='MpServer', x=73.81, y=25.00, z=445.56], EntityCyclops['独眼巨人'/288, l='MpServer', x=71.75, y=25.00, z=432.19], EntityImp['瘸腿僵尸'/289, l='MpServer', x=78.63, y=25.00, z=440.91], EntitySkeletonWarrior['骷髅剑士'/290, l='MpServer', x=79.22, y=25.00, z=439.28], EntitySkeletonWarrior['骷髅剑士'/293, l='MpServer', x=92.59, y=25.00, z=448.16], EntitySkeletonWarrior['骷髅剑士'/294, l='MpServer', x=85.50, y=25.00, z=440.50], EntitySkeletonWarrior['骷髅剑士'/295, l='MpServer', x=81.69, y=25.00, z=443.46], EntityImp['瘸腿僵尸'/296, l='MpServer', x=86.50, y=25.00, z=439.50], EntityImp['瘸腿僵尸'/297, l='MpServer', x=84.31, y=25.00, z=443.16], EntitySpider['蜘蛛'/298, l='MpServer', x=79.81, y=31.18, z=458.28], EntityWolf['狼'/299, l='MpServer', x=118.75, y=64.00, z=421.31], EntityXPOrb['经验球'/300, l='MpServer', x=83.47, y=25.25, z=450.94], EntityXPOrb['经验球'/301, l='MpServer', x=83.50, y=25.25, z=453.28], EntityVoidFiend['虚空领主小怪'/3631, l='MpServer', x=71.00, y=80.00, z=418.22], EntityVoidFiend['虚空领主小怪'/3632, l='MpServer', x=71.94, y=81.00, z=419.13], EntityWolf['狼'/305, l='MpServer', x=133.44, y=68.00, z=416.13], EntityZombie['僵尸'/306, l='MpServer', x=85.50, y=15.00, z=476.50], EntityBat['蝙蝠'/307, l='MpServer', x=61.30, y=20.50, z=484.44], EntitySkeleton['骷髅'/308, l='MpServer', x=26.50, y=21.00, z=448.50], EntitySkeleton['骷髅'/309, l='MpServer', x=13.50, y=13.00, z=447.50], EntityBat['蝙蝠'/314, l='MpServer', x=145.33, y=21.14, z=449.26], EntityZombie['僵尸'/315, l='MpServer', x=99.72, y=16.00, z=477.22], EntityZombie['僵尸'/316, l='MpServer', x=100.50, y=16.00, z=469.50], EntityZombie['僵尸'/317, l='MpServer', x=99.31, y=16.00, z=472.44], EntitySkeleton['骷髅'/318, l='MpServer', x=96.50, y=16.00, z=469.50], EntitySkeleton['骷髅'/319, l='MpServer', x=101.78, y=15.00, z=479.78], EntityBat['蝙蝠'/320, l='MpServer', x=79.46, y=17.62, z=478.85], EntitySkeleton['骷髅'/321, l='MpServer', x=0.53, y=13.00, z=449.06], EntityBat['蝙蝠'/322, l='MpServer', x=16.92, y=17.92, z=470.27], EntityBat['蝙蝠'/323, l='MpServer', x=138.59, y=19.10, z=459.13], EntityBat['蝙蝠'/326, l='MpServer', x=72.78, y=19.87, z=490.43], EntityCreeper['爬行者'/70, l='MpServer', x=7.50, y=28.00, z=359.50], EntityBat['蝙蝠'/327, l='MpServer', x=48.75, y=20.10, z=488.88], EntityZombie['僵尸'/71, l='MpServer', x=9.50, y=28.00, z=365.50], EntityItem['item.tile.flower2.poppy'/74, l='MpServer', x=13.13, y=23.13, z=369.13], EntitySkeleton['骷髅'/331, l='MpServer', x=46.50, y=20.00, z=485.50], EntityItem['item.tile.flower2.allium'/75, l='MpServer', x=13.13, y=23.13, z=369.13], EntityZombie['僵尸'/333, l='MpServer', x=-0.50, y=13.00, z=447.50], EntityBat['蝙蝠'/79, l='MpServer', x=4.38, y=41.10, z=398.75], EntityZombie['僵尸'/336, l='MpServer', x=102.69, y=15.00, z=480.69], EntityBat['蝙蝠'/80, l='MpServer', x=4.29, y=42.48, z=402.47], EntityZombie['僵尸'/338, l='MpServer', x=0.34, y=19.00, z=469.50], EntityZombie['僵尸'/339, l='MpServer', x=1.50, y=19.00, z=471.50], EntitySkeleton['骷髅'/340, l='MpServer', x=5.56, y=17.00, z=471.50], EntityItem['item.item.trollaxe'/3412, l='MpServer', x=73.41, y=25.13, z=446.00], EntitySkeleton['骷髅'/341, l='MpServer', x=1.31, y=19.00, z=469.50], EntityEnderman['末影人'/85, l='MpServer', x=22.50, y=26.00, z=374.09], EntityItem['item.item.metalCoin'/3413, l='MpServer', x=73.47, y=25.13, z=447.09], EntitySpider['蜘蛛'/86, l='MpServer', x=27.28, y=26.00, z=375.28], EntitySpider['蜘蛛'/88, l='MpServer', x=28.28, y=50.00, z=386.72], EntityZombie['僵尸'/345, l='MpServer', x=8.69, y=35.00, z=465.31], EntityCreeper['爬行者'/346, l='MpServer', x=15.50, y=35.00, z=473.50], EntityCreeper['爬行者'/347, l='MpServer', x=15.50, y=35.00, z=474.50], EntityBat['蝙蝠'/348, l='MpServer', x=2.71, y=36.58, z=463.53], EntityChicken['鸡'/92, l='MpServer', x=40.41, y=68.00, z=337.56], EntityChicken['鸡'/93, l='MpServer', x=33.50, y=67.00, z=337.50], EntityChicken['鸡'/95, l='MpServer', x=32.50, y=67.00, z=339.50], EntityItem['item.tile.flower2.allium'/97, l='MpServer', x=38.88, y=19.13, z=365.13], EntityWolf['狼'/98, l='MpServer', x=56.50, y=70.00, z=366.78], EntityChicken['鸡'/99, l='MpServer', x=37.53, y=68.00, z=395.53], EntityChicken['鸡'/100, l='MpServer', x=42.28, y=69.00, z=399.97], EntityBat['蝙蝠'/356, l='MpServer', x=85.29, y=55.02, z=486.51], EntityChicken['鸡'/101, l='MpServer', x=37.56, y=69.00, z=397.47], EntityChicken['鸡'/102, l='MpServer', x=34.59, y=71.00, z=409.41], EntityCow['牛'/359, l='MpServer', x=17.69, y=68.00, z=488.44], EntityCow['牛'/360, l='MpServer', x=14.75, y=67.00, z=487.19], EntityCow['牛'/361, l='MpServer', x=16.41, y=69.00, z=489.63], EntityCow['牛'/362, l='MpServer', x=5.94, y=68.00, z=483.09], EntityWolf['狼'/110, l='MpServer', x=50.63, y=67.00, z=375.59], EntityWolf['狼'/111, l='MpServer', x=44.66, y=68.00, z=378.25], EntityBat['蝙蝠'/112, l='MpServer', x=57.50, y=48.10, z=384.53], EntityItem['item.tile.cloth.white'/113, l='MpServer', x=58.69, y=67.13, z=394.38], EntityItem['item.tile.cloth.black'/114, l='MpServer', x=51.75, y=67.13, z=391.94], EntityItem['item.tile.cloth.white'/115, l='MpServer', x=55.88, y=68.13, z=392.56], EntityItem['item.tile.cloth.white'/116, l='MpServer', x=53.09, y=67.13, z=390.94], EntityWolf['狼'/117, l='MpServer', x=56.28, y=66.00, z=387.00], EntityItem['item.tile.cloth.white'/118, l='MpServer', x=60.03, y=66.13, z=392.44], EntityWolf['狼'/119, l='MpServer', x=62.28, y=69.00, z=391.16], EntityItem['item.tile.cloth.white'/120, l='MpServer', x=56.59, y=64.13, z=412.81], EntityWolf['狼'/121, l='MpServer', x=57.06, y=67.00, z=407.53], EntityItem['item.tile.cloth.brown'/122, l='MpServer', x=54.91, y=66.13, z=403.81], EntityCow['牛'/379, l='MpServer', x=-4.47, y=71.00, z=486.81], EntityItem['item.tile.cloth.white'/123, l='MpServer', x=54.13, y=66.13, z=402.75], EntityWolf['狼'/130, l='MpServer', x=66.44, y=66.00, z=381.09], EntityZombie['僵尸'/131, l='MpServer', x=73.50, y=45.00, z=414.50], EntityCreeper['爬行者'/132, l='MpServer', x=68.50, y=45.00, z=415.50], EntityCreeper['爬行者'/133, l='MpServer', x=69.50, y=45.00, z=415.50], EntityItem['item.tile.sapling.spruce'/134, l='MpServer', x=66.88, y=66.13, z=411.88], EntityWolf['狼'/140, l='MpServer', x=90.31, y=72.00, z=359.66], EntityBat['蝙蝠'/141, l='MpServer', x=92.39, y=61.01, z=412.26], EntityWolf['狼'/149, l='MpServer', x=100.50, y=68.00, z=388.50], EntityWolf['狼'/150, l='MpServer', x=97.00, y=69.00, z=388.69], EntityWolf['狼'/151, l='MpServer', x=100.75, y=68.00, z=401.50], EntityWolf['狼'/154, l='MpServer', x=112.75, y=68.00, z=394.69], EntityZombie['僵尸'/155, l='MpServer', x=117.50, y=53.00, z=412.50], EntityZombie['僵尸'/156, l='MpServer', x=123.50, y=53.00, z=412.50], EntityWolf['狼'/157, l='MpServer', x=124.78, y=68.00, z=401.31], EntityWolf['狼'/158, l='MpServer', x=112.69, y=67.00, z=405.50], EntityWolf['狼'/159, l='MpServer', x=128.13, y=65.00, z=411.44], EntityWolf['狼'/160, l='MpServer', x=124.50, y=65.00, z=414.50], EntityWolf['狼'/161, l='MpServer', x=123.31, y=69.00, z=396.75], EntityCreeper['爬行者'/171, l='MpServer', x=143.50, y=17.00, z=362.50], EntityZombie['僵尸'/172, l='MpServer', x=136.78, y=19.00, z=361.31], EntityZombie['僵尸'/173, l='MpServer', x=140.53, y=19.00, z=365.03], EntityItem['item.item.emerald'/3508, l='MpServer', x=81.78, y=25.13, z=445.47], EntityItem['item.item.metalCoin'/3509, l='MpServer', x=82.56, y=25.13, z=445.81], EntityBat['蝙蝠'/996, l='MpServer', x=124.77, y=51.54, z=434.39], EntityBat['蝙蝠'/999, l='MpServer', x=127.49, y=52.79, z=438.30], EntityBat['蝙蝠'/1002, l='MpServer', x=125.26, y=51.58, z=437.58], EntityCreeper['爬行者'/1274, l='MpServer', x=71.88, y=85.00, z=421.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 508642248 bytes (485 MB) / 855638016 bytes (816 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (IvToolkit-1.2.2.jar) 
	UCHIJAAAA	reccomplex{0.9.7.1.8} [Recurrent Complex TF-E] (RecurrentComplex-0.9.7.1.8.jar) 
	UCHIJAAAA	gibby_dungeons{1.4.8.1} [Arcana RPG] (Arcana-Rpg-Continuation-1.7.10-1.4.8.4.jar) 
	UCHIJAAAA	craftguide{1.7.1.0} [CraftGuide] (CraftGuide-1.7.1.0-forge.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (ReiMinimap-1.7.10-3.6_CN by wolski.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 537.42' Renderer: 'NVIDIA GeForce GTX 1660/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

### Description

When I take blade of paladin right click, the game crashes.
This problem still exists even in the latest version of the original mod or in version 1.3

**Comment by quentin452** [comment]
do you have full logs?

**Comment by quentin452** [comment]
[unzipme.zip](https://github.com/quentin452/Arcana-RPG/files/13983539/unzipme.zip)
try this

**Comment by 167OSS** [comment]
Okay, thanks, seems to be no problem.
